# NOTE: This module is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the module manually.

defmodule HarmonyConnect.Model.AllInfo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :version,
    :links
  ]

  @type t :: %__MODULE__{
    version: String.t,
    links: AllInfoLinks
  }
end

defimpl Poison.Decoder, for: HarmonyConnect.Model.AllInfo do
  import HarmonyConnect.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:links, :struct, HarmonyConnect.Model.AllInfoLinks, options)
  end
end

