# NOTE: This module is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the module manually.

defmodule HarmonyConnect.Model.AllInfoLinks do
  @moduledoc """
  Links to internal paths of the application
  """

  @derive [Poison.Encoder]
  defstruct [
    :chains
  ]

  @type t :: %__MODULE__{
    chains: String.t
  }
end

defimpl Poison.Decoder, for: HarmonyConnect.Model.AllInfoLinks do
  def decode(value, _options) do
    value
  end
end

