# NOTE: This module is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the module manually.

defmodule HarmonyConnect.Model.ChainShort do
  @moduledoc """
  Represents a list of Factom chains that have been or will be saved to the blockchain.
  """

  @derive [Poison.Encoder]
  defstruct [
    :chain_id,
    :entry_hash,
    :stage
  ]

  @type t :: %__MODULE__{
    chain_id: String.t,
    entry_hash: String.t,
    stage: String.t
  }
end

defimpl Poison.Decoder, for: HarmonyConnect.Model.ChainShort do
  def decode(value, _options) do
    value
  end
end

