# NOTE: This module is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the module manually.

defmodule HarmonyConnect.Model.ChainDataDblock do
  @moduledoc """
  Represents the Directory Block that relates to this chain. This will be null if the chain is not at least at the &#x60;factom&#x60; immutability stage.
  """

  @derive [Poison.Encoder]
  defstruct [
    :keymr,
    :height,
    :href
  ]

  @type t :: %__MODULE__{
    keymr: String.t | nil,
    height: integer() | nil,
    href: String.t | nil
  }
end

defimpl Poison.Decoder, for: HarmonyConnect.Model.ChainDataDblock do
  def decode(value, _options) do
    value
  end
end

