# NOTE: This module is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the module manually.

defmodule HarmonyConnect.Model.ChainDataEntries do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :href
  ]

  @type t :: %__MODULE__{
    href: String.t
  }
end

defimpl Poison.Decoder, for: HarmonyConnect.Model.ChainDataEntries do
  def decode(value, _options) do
    value
  end
end

