# NOTE: This module is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the module manually.

defmodule HarmonyConnect.Model.Chain do
  @moduledoc """
  Represents a list of Factom entries that have been or will be saved to the blockchain.
  """

  @derive [Poison.Encoder]
  defstruct [
    :data
  ]

  @type t :: %__MODULE__{
    data: ChainData
  }
end

defimpl Poison.Decoder, for: HarmonyConnect.Model.Chain do
  import HarmonyConnect.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:data, :struct, HarmonyConnect.Model.ChainData, options)
  end
end

