# NOTE: This module is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the module manually.

defmodule HarmonyConnect.Model.ChainLink do
  @moduledoc """
  An object that contains the Chain Hash (ID) as well as a URL for the chain.
  """

  @derive [Poison.Encoder]
  defstruct [
    :chain_id,
    :href
  ]

  @type t :: %__MODULE__{
    chain_id: String.t,
    href: String.t
  }
end

defimpl Poison.Decoder, for: HarmonyConnect.Model.ChainLink do
  def decode(value, _options) do
    value
  end
end

