# NOTE: This module is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the module manually.

defmodule HarmonyConnect.Model.ChainList do
  @moduledoc """
  Represents a list of Factom entries that have been or will be saved to the blockchain.
  """

  @derive [Poison.Encoder]
  defstruct [
    :data,
    :offset,
    :limit,
    :count
  ]

  @type t :: %__MODULE__{
    data: [ChainListData],
    offset: integer(),
    limit: integer(),
    count: integer()
  }
end

defimpl Poison.Decoder, for: HarmonyConnect.Model.ChainList do
  import HarmonyConnect.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:data, :list, HarmonyConnect.Model.ChainListData, options)
  end
end

