# NOTE: This module is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the module manually.

defmodule HarmonyConnect.Model.EntryDataEblock do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :keymr,
    :href
  ]

  @type t :: %__MODULE__{
    keymr: String.t | nil,
    href: String.t | nil
  }
end

defimpl Poison.Decoder, for: HarmonyConnect.Model.EntryDataEblock do
  def decode(value, _options) do
    value
  end
end

