# NOTE: This module is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the module manually.

defmodule HarmonyConnect.Model.EntrySearchResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :data,
    :offset,
    :limit,
    :count
  ]

  @type t :: %__MODULE__{
    data: [EntrySearchResponseData],
    offset: String.t,
    limit: String.t,
    count: String.t
  }
end

defimpl Poison.Decoder, for: HarmonyConnect.Model.EntrySearchResponse do
  import HarmonyConnect.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:data, :list, HarmonyConnect.Model.EntrySearchResponseData, options)
  end
end

