# NOTE: This module is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the module manually.

defmodule HarmonyConnect.Model.EntryListData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :entry_hash,
    :chain,
    :created_at,
    :href
  ]

  @type t :: %__MODULE__{
    entry_hash: String.t,
    chain: EntryListChain,
    created_at: String.t | nil,
    href: String.t
  }
end

defimpl Poison.Decoder, for: HarmonyConnect.Model.EntryListData do
  import HarmonyConnect.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:chain, :struct, HarmonyConnect.Model.EntryListChain, options)
  end
end

