# NOTE: This module is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the module manually.

defmodule HarmonyConnect.Model.EntryData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :entry_hash,
    :chain,
    :created_at,
    :external_ids,
    :content,
    :stage,
    :eblock
  ]

  @type t :: %__MODULE__{
    entry_hash: String.t | nil,
    chain: EntryLinkChain | nil,
    created_at: String.t | nil,
    external_ids: [String.t] | nil,
    content: String.t | nil,
    stage: String.t | nil,
    eblock: EntryDataEblock | nil
  }
end

defimpl Poison.Decoder, for: HarmonyConnect.Model.EntryData do
  import HarmonyConnect.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:chain, :struct, HarmonyConnect.Model.EntryLinkChain, options)
    |> deserialize(:eblock, :struct, HarmonyConnect.Model.EntryDataEblock, options)
  end
end

