# NOTE: This module is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the module manually.

defmodule HarmonyConnect.Model.SearchBody do
  @moduledoc """
  The external IDs of the chains or entries you want to retrieve. You must enter these External IDs in Base64 format.
  """

  @derive [Poison.Encoder]
  defstruct [
    :external_ids
  ]

  @type t :: %__MODULE__{
    external_ids: [String.t]
  }
end

defimpl Poison.Decoder, for: HarmonyConnect.Model.SearchBody do
  def decode(value, _options) do
    value
  end
end

