# NOTE: This module is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the module manually.

defmodule HarmonyConnect.Api.Info do
  @moduledoc """
  API calls for all endpoints tagged `Info`.
  """

  alias HarmonyConnect.Connection
  import HarmonyConnect.RequestBuilder


  @doc """
  API Info
  Request general information about the Connect API such as the version and available endpoints.

  ## Parameters

  - connection (HarmonyConnect.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, %HarmonyConnect.Model.AllInfo{}} on success
  {:error, info} on failure
  """
  @spec get_api_info(Tesla.Env.client, keyword()) :: {:ok, HarmonyConnect.Model.AllInfo.t} | {:error, Tesla.Env.t}
  def get_api_info(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%HarmonyConnect.Model.AllInfo{})
  end
end
