# NOTE: This module is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the module manually.

defmodule HarmonyConnect.Connection do
  @moduledoc """
  Handle Tesla connections for HarmonyConnect.
  """

  use Tesla

  @base_url "https://connect-shared-sandbox-2445582615332.production.gw.apicast.io/v1"

  @doc """
  Configure a client connection using API Keys

  ## Parameters

  - app_id (binary): AppId used for authentication
  - app_key (binary): AppKey used for authentication
  

  # Returns

  Tesla.Env.client
  """
  @spec new(binary, binary) :: Tesla.Env.client
  def new(app_id, app_key),
    do: new(@base_url, app_id, app_key)

  @spec new(binary, binary, binary) :: Tesla.Env.client
  def new(base_url, app_id, app_key) do
    Tesla.build_client([
      {Tesla.Middleware.BaseUrl, base_url},
      Tesla.Middleware.JSON,
      {Tesla.Middleware.Headers, %{
        "app_id" => app_id, "app_key" => app_key
        }
      }
    ])
  end
end
